version: '3'
services:
  my-mariadb:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: my-mariadb
    image: my-mariadb
    ports:
      - 3306:3306

  eureka:
    build:
      context: ./
      dockerfile: ./eureka/Dockerfile
    restart: always
    ports:
      - 8761:8761
    container_name: eureka
    hostname: eureka
    image: eureka

  config:
    build:
      context: ./
      dockerfile: ./config/Dockerfile
    restart: always
    ports:
      - 8888:8888
    container_name: config
    hostname: config
    image: config


  gateway:
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
    restart: always
    ports:
      - 9000:9000
    container_name: gateway
    hostname: gateway
    image: gateway

  zipkin:
    build:
      context: ./
      dockerfile: ./graphical/zipkin/Dockerfile
    restart: always
    ports:
      - 9411:9411
    container_name: zipkin
    hostname: zipkin
    image: zipkin

  admin-server:
    build:
      context: ./
      dockerfile: ./graphical/admin-server/Dockerfile
    restart: always
    ports:
      - 9010:9010
    container_name: admin-server
    hostname: admin-server
    image: admin-server

  user-service:
    build:
      context: ./
      dockerfile: ./services/user-server/Dockerfile
    restart: always
    ports:
      - 9040:9040
    container_name: user-server
    hostname: user-server
    image: user-server
