version: '3'
services:
  eureka:
    build:
      context: ./
      dockerfile: ./eureka/Dockerfile
    restart: always
    ports:
      - 8761:8761
    container_name: eureka
    hostname: eureka
    image: eureka

  gateway:
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
    restart: always
    ports:
      - 9000:9000
    container_name: gateway
    hostname: gateway
    image: gateway

  zipkin:
    build:
      context: ./
      dockerfile: ./graphical/zipkin/Dockerfile
    restart: always
    ports:
      - 9411:9411
    container_name: zipkin
    hostname: zipkin
    image: zipkin

  admin-server:
    build:
      context: ./
      dockerfile: ./graphical/admin-server/Dockerfile
    restart: always
    ports:
      - 9010:9010
    container_name: admin-server
    hostname: admin-server
    image: admin-server
