version: '3'
services:
  pl-eureka:
    build:
      context: ./
      dockerfile: ./eureka/Dockerfile
    restart: always
    ports:
      - 8761:8761
    container_name: pl-eureka
    hostname: eureka
    image: pl-eureka

  pl-gateway:
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
    restart: always
    ports:
      - 9000:9000
    container_name: pl-gateway
    hostname: gateway
    image: pl-gateway

  pl-zipkin:
    build:
      context: ./
      dockerfile: ./graphical/zipkin/Dockerfile
    restart: always
    ports:
      - 9411:9411
    container_name: pl-zipkin
    hostname: zipkin
    image: pl-zipkin

  pl-admin-server:
    build:
      context: ./
      dockerfile: ./graphical/admin-server/Dockerfile
    restart: always
    ports:
      - 9010:9010
    container_name: pl-admin-server
    hostname: admin-server
    image: pl-admin-server
