spring:
  application:
    name: auth-server
#  security:
#    user:
#      name: user
#      password: 123456

# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka/

---
# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.103:3306/oauth_learn?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  redis:
    port: 6379
    host: 192.168.1.103
  # 运行bean覆盖
  main:
    allow-bean-definition-overriding: true
