spring:
  #路由
  cloud:
    gateway:
      discovery:
        locator:
          #开启服务注册和发现的功能 可以通过其他服务的serviceId来转发到具体的服务实例
          enabled: false
          #将服务名称配置为小写，注册中心的服务名称默认被转换为大写
          lonwer-case-service-id: true
      routes:
        # 认证中心
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 用户服务
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        # 动态服务
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/event/**
          filters:
            - StripPrefix=1
  #应用监控
  boot:
    admin:
      client:
        url: http://admin-server:9010
  #服务链路追踪
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1
