spring:
  datasource:
    name: user-service
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      #基本属性
      url: jdbc:p6spy:mysql://192.168.1.103:3306/user_learn?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
      username: root
      password: 123456
      #初始化时建立物理连接的个数
      initial-size: 1
      #最大连接数
      max-active: 20
      #最小连接池数量
      min-idle: 1
      #获取连接等待超时时间,毫秒
      max-wait: 60000
      #检查连接是否有效
      validation-query: select 1
      #检测连接是否有效的超时时间
      validation-query-timeout: 2000
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      test-while-idle: true
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
---
spring:
  #应用监控
  boot:
    admin:
      client:
        url: http://admin-server:9010
  #服务链路追踪
  zipkin:
    base-url: http://zipkin:9411
    sleuth:
      sampler:
        probability: 1

