#mybatis-plus 全局配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    db-config:
      db-type: mysql
      field-strategy: not_empty
      id-type: id_worker
      #逻辑已删除值
      logic-delete-value: 0
      # 逻辑未删除值
      logic-not-delete-value: 1
    banner: false
    super-mapper-class: com.github.pengliangs.common.core.dao.BaseDAO

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    mapper:
      PROPAGATE_TRANSIENT_MARKER: true
    parser:
      ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER: true
  liquibase:
    enabled: false
  aop:
    auto: true
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size: 5GB